import type { NextPage } from "next";
import Head from "next/head";

  const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to a <a href="http://nextjs.org">NextJS</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus minus odit culpa quos rem cum quod esse consequatur dolor eum nobis, dolorem voluptatem nemo explicabo. Error sit maxime perspiciatis reiciendis?
        </p>
      </main>
    </>
    );
  }
export default Home
