import type { NextPage } from "next";
import Head from "next/head";

  const Products: NextPage = () => {
  return (
    <>
      <Head>
        <title>Nossos Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Nossos Produtos</h1>
      </main>
    </>
    );
  }
export default Products
