import CartTable from "@/components/CartTable";
import Header from "../src/components/Header";
import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "reactstrap";
import CartTotal from "@/components/CartTotal";

  const Cart: NextPage = () => {
  return (
    <>
      <Head>
        <title>Carrinho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Container className="mb-5">
        <h1 className="my-5">Carrinho</h1>
        <CartTable />
        <CartTotal />
        </Container>
      </main>
    </>
    );
  }
export default Cart
