import { GetStaticProps, NextPage } from "next";
import ProductsList from "@/components/ProductLists";
import Header from "../src/components/Header";
import Head from "next/head";
import { Container } from "reactstrap";
import { ProductType, fetchProducts } from "@/services/products";
import { ReactNode } from "react";

// para obter os produtos de forma estatica
// Este é um método especial do Next.js que é executado no momento da construção da página. Ele chama a função fetchProducts (que busca todos os produtos) e retorna um objeto contendo as propriedades que serão passadas para a página. Neste caso, a propriedade products contém a lista de produtos.
export const getStaticProps: GetStaticProps = async () => {
  // vai chamar a requisição feita na pasta services  
  const products = await fetchProducts()
  return {props: {products}}
}
  // Este é o componente da página em si. Ele recebe as propriedades `products` (a lista de produtos obtidos na função `getStaticProps`). Ele renderiza um título, o componente `Header`, e depois uma lista de produtos usando o componente `ProductsList`. Note que `ProductsList products={props.products!}` está renderizando o componente `ProductsList` e passando a lista de produtos como propriedade. O `!` após `props.products` é usado para indicar que a propriedade não será nula.

  const Products: NextPage = (props: {
    children?: ReactNode
    products?: ProductType[]
  }) => {
  return (
    <>
      <Head>
        <title>Nossos Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Container className='mb-5'>
        <h1>Nossos Produtos</h1>
        {<ProductsList products={props.products!} />}
        </Container>
      </main>
    </>
    );
  }
export default Products
